[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "movie-poster-genre"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "torch",
    "torchvision",
    "datasets",
    "pillow",
    "pandas",
    "scikit-learn",
    "pyyaml",
    "matplotlib",
    "jupyter",
    "tensorboard",
    "seaborn",
]

[tool.setuptools.packages.find]
include = ["data*", "data_loader*", "models*", "trainer*"]