data:
  save_dir: /gpfs/home/khousto4/movie-poster-genre-data/images
  metadata_path: /gpfs/home/khousto4/movie-poster-genre-data/metadata.csv
  img_size: 224
  quality: 95

training:
  batch_size: 64
  lr: 0.0001
  epochs: 20

experiment:
  name: "baseline_v6"
  notes: "lr=0.0001, batch=64, epochs=20, dropout=0.6, no augmentation"